version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '8088:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - mysql

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql1
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: formulario
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./data-db:/var/lib/mysql
    restart: always

    

