name: Primer flujo de trabajo Curro
on: workflow_dispatch
jobs:
  primer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Saluda
        run: echo "¡Hola Curro!"
      - name: despedida
        run: echo "¡Adios Curro!"