name: Pipeline - Lint PHP

on: 
  workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:    
      - name: Descarga repo
        uses: actions/checkout@v3
      - name: Linting PHP
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: './scr/web/srcweb'
