name: Pipeline - Fase Deploy ECR

on: 
  workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga repo
        uses: actions/checkout@v3
      
      - name: Configuración credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Login en AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, push image Proxy en ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PROXY: app-api-proxy
          IMAGE_PROXY_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_PROXY:$IMAGE_PROXY_TAG . -f src/web/Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_PROXY:$IMAGE_PROXY_TAG
          echo "Cambios realizados Proxy"

      - name: Build, tag, push image API en ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_API: app-api-api
          IMAGE_API_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_API_TAG . -f src/app/Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_API_TAG
          echo "Cambios realizados Api"
          
        