name: Pipeline - Esqueleto

on: 
  push:
    branches:
      - dev
      - master


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:    
      - name: Descarga repo
        run: |
          echo "Codigo descargado"
     
  
      - name: Terraform Plan
        if: ${{ github.ref == 'ref/heads/dev' }}
        run: |
          echo "Terraform Plan de DEV"
      
      - name: Terraform Apply DEV
        if: ${{ github.ref == 'ref/heads/dev' }}
        run: |         
          echo "Terraform Apply de DEV"

      - name: Terraform Apply MASTER
        if: ${{ github.ref == 'ref/heads/master' }}
        run: |         
          echo "Terraform Apply de MASTER"

   #   - name: Terraform Destroy
   #     run: |
   #       docker-compose -f deploy/docker-compose.yml run --rm terraform init     
   #       docker-compose -f deploy/docker-compose.yml run --rm terraform destroy -auto-approve
          